#**************************logging config***********************************************
logging:
  config:
  exception-conversion-word:
  file: d:/data/logs/api-web.log
  register-shutdown-hook: true
  level:
    root: INFO
    org.apache: WARN
    org.springframework: WARN
    org.springframework.boot.context.embedded.tomcat: WARN
    com.teague: DEBUG
  pattern:
      file: '[%d{yyyy-MM-dd HH:mm:ss.SSS}]  [%thread] %-5level %logger{50} - %msg%n'
      console: '[%d{yyyy-MM-dd HH:mm:ss}] [%-5p] [%-8t]  [%c] L:%-3L - %m%n'
      level: debug

server:
  port: 80

multipart:
     maxFileSize: 10Mb
     maxRequestSize: 100Mb

mybatis:
    datasrc1:
       driver: 'org.postgresql.Driver'
       url: 'jdbc:postgresql://119.23.29.154:5432/postgres'
       username: postgres
       password: postgres
       maxPoolSize: 500
       minPoolSize: 20
       initialPoolSize: 20
       maxIdleTime: 60　
       checkoutTimeout: 18000
       acquireIncrement: 10
       acquireRetryAttempts: 1
       acquireRetryDelay: 1000
       idleConnectionTestPeriod: 60

web:
     upload-path: 'C:/static/'
spring:
     mvc:
          static-path-pattern: '/**'
#          view:
#             prefix: '/'
#             suffix: .html       
     thymeleaf: 
         prefix: 'file:${web.upload-path}'
         suffix: .html
         mode: HTML5
         encoding: UTF-8 
         content-type: text/html
         cache: false        
     resources:
           static-locations: 'file:${web.upload-path}'
     http:
           multipart:
               maxFileSize: 100Mb
               maxRequestSize:
     datasource:
          url: 'jdbc:postgresql://119.23.29.154:5432/postgres'
          username: 'postgres'
          password: 'postgres'
          driver-class-name: 'org.postgresql.Driver'










